apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-web-front-rangulo
  labels:
    app: mi-web-front-rangulo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-web-front-rangulo
  template:
    metadata:
      labels:
        app: mi-web-front-rangulo
    spec:
      containers:
        - name: mi-web-front-rangulo
          image: rangulo1972/frontend-k8-action:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mi-web-front-rangulo-service
spec:
  selector:
    app: mi-web-front-rangulo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer